### ISSUE TITLE
When I generate a system with two asteroid belts, one of them does not seem to work properly when clicked.

### ISSUE THREAD

**Issue by slambert-msft** [Anyndil/planetary-system-generator#1]
I've only given a cursory read through some saved system json, but it looks like perhaps it was a bug in the initial generation of the system.    I wonder if it's related to the fact that the asteroid belts aren't given unique names?

I generated a couple of systems with two asteroid belts, and in each the json between the two is different.  In fact, in each case the broken asteroid belt has the suspicious property '"id": 24,'

I also see that clicking it results in an exception, but I suspect that's related to the broken generation.

(PS, thanks for this fantastic tool!  This is the only way I found to contact you...)

**Comment by sum1els-com** [comment]
And now I realize I was using my old work account to leave the message, but I've retired and should stick to this account instead.  =]

**Comment by sum1els-com** [comment]
I have tracked the error down to asteroid belts created by generateAsteroidBeltsFn() which appears to convert smaller planets down-system from a gas giant into an asteroid belt (RIP class M planet next to a class J!)  I'm still trying to track down the details, but I generated a system with 3 asteroid belts, but only one of them was generated using generateAsteroidBeltsFn() and that's the one that doesn't work right.  I still need to figure out how the others were generated and see if I can figure out what's missing.

**Comment by sum1els-com** [comment]
OK, I think it's the temperature calculation that's the biggest problem, but really the asteroid belt should be generated the same way as a normal planet, including the cleanup section.  I'll create a PR with a possible solution soon.

**Comment by sum1els-com** [comment]
OK, I've got a fix and I tested it; now the generateAsteroidBeltsFn() works properly.  I'd love to push this change and create a PR, but I guess I don't have access.

**Comment by sum1els-com** [comment]
It looks like the code was merged, and this issue is now closed!
